When building the BOM also test the http-booster
Implements: SB-814

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,6 +41,18 @@ jobs:
 
           popd
 
+    - run:
+        name: Download http-booster
+        command: |
+          pushd /tmp
+          git clone https://snowdrop/spring-boot-http-booster.git
+          cd spring-boot-http-booster
+
+          # Done in order to cache maven artifacts
+          mvn dependency:go-offline
+
+          popd
+
     - save_cache:
         paths:
         - ~/.m2
@@ -75,6 +87,27 @@ jobs:
           sleep 10
           oc login -u system:admin
           echo "Configured OpenShift cluster : v3.9.0"
+
+    - run:
+        name: Test http booster
+        command: |
+          bom_version=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
+          versionRE='^([1-9]\.[0-9]\.[0-9]+).*'
+          if [[ "${bom_version}" =~ ${versionRE} ]]; then
+            version_numbers_only=${BASH_REMATCH[1]}
+            spring_boot_release="${version_numbers_only}.RELEASE"
+
+            echo "Testing http-booster using"
+            echo "spring-boot.bom.version=${bom_version}"
+            echo "spring-boot.version=${spring_boot_release}"
+
+            pushd /tmp/spring-boot-http-booster
+            mvn clean verify -Popenshift,openshift-it -Dspring-boot.bom.version=${bom_version} -Dspring-boot.version=${spring_boot_release}
+
+          else
+            echo "The BOM version is invalid!"
+            exit 1
+          fi
 
     - run:
         name: Launch testsuite
